# Base URL for the site
baseurl = "https://usererror.github.io/"

# Language for the site
languageCode = "en-us"

# Number of posts to show before paginating
paginate = 7

# Theme for the site
theme = "hello-friend"

[author]
  name = "usererror"

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showReadingTime = true

[languages]
  [languages.en]
    title = "Welcome to the Errordome"
    subtitle = "Computers are a fad."
    keywords = ""
    copyright = "Copyright © 2019 The Coalition of Atheists and Orthodox Catholics United Against Creeping Agnosticism. All rights reserved."
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"

    [languages.en.params.logo]
      logoText = "usererror"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/about"
